// إهدنا — دليل المشاريع المصوّر (أيقونات من ملصق المؤسسة + شرح مبسّط)
window.IHDINA_SHOWCASE = {
  core: [
    {ic:'p00', n:{ar:"التفسير التفاعلي الذكي",en:"Interactive Smart Tafsir"},
      d:{ar:"قلب المؤسسة: يحوّل القرآن من نصٍّ يُقرأ إلى تجربةٍ تُعاش، يحاكي النزول الأول ويربط كل كتلة بالسيرة والتطبيق.",
         en:"The heart of the platform: turns the Qur'an from text into a lived experience, simulating the first revelation."}},
    {ic:'p01', n:{ar:"مفاعل الهداية",en:"The Guidance Reactor"},
      d:{ar:"يرتّب دخول الكتل المعرفية العابرة للسور ويدمجها في نظامٍ تربويٍّ معرفيٍّ حركيٍّ متكامل.",
         en:"Sequences cross-chapter knowledge blocks into one integrated learning system."}},
    {ic:'p02', n:{ar:"الكتل المعرفية",en:"Knowledge Blocks"},
      d:{ar:"الوحدة المعرفية الصغرى غير القابلة للتجزئة — بها يُرتّب القرآن حسب نموّ المفهوم لا حسب المصحف.",
         en:"The indivisible unit that orders the Qur'an by the growth of meaning."}},
    {ic:'p03', n:{ar:"بوصلة الشخصية",en:"Personality Compass"},
      d:{ar:"تحليل شخصيتك على منهج القرآن (القوي الأمين) ومراتب النفس، لتوجيه رحلتك بما يناسبك.",
         en:"A Qur'anic personality analysis that tailors your journey to who you are."}},
    {ic:'p04', n:{ar:"نبض البيئة",en:"Environment Pulse"},
      d:{ar:"تحليل بيئتك (داعمة/محايدة/صعبة) على منهج «أمّ القرى» لاختيار الاستراتيجية الملائمة.",
         en:"Analyzes your environment to choose the right strategy for your context."}},
    {ic:'p05', n:{ar:"ورد المحاسبة اليومية",en:"Daily Accountability Wird"},
      d:{ar:"قياسٌ يوميٌّ موزونٌ على المحاور الثلاثة يحوّل الفهم إلى سلوكٍ يُرى ويُقاس.",
         en:"A balanced daily measure turning understanding into visible, measurable conduct."}},
    {ic:'p06', n:{ar:"حصن الإيمان",en:"Fortress of Faith"},
      d:{ar:"رعاية المسلم الجديد واحتضانه في بيئةٍ آمنةٍ تثبّته على الحق بعد الشهادة.",
         en:"Nurtures and protects the new Muslim in a safe environment after the shahada."}},
    {ic:'p07', n:{ar:"أكاديمية الهداية",en:"Guidance Academy"},
      d:{ar:"تعليمٌ وتأهيلٌ منهجيٌّ متدرّج للمهتدين والدعاة، من التأسيس إلى القيادة.",
         en:"Structured education and training for new Muslims and callers alike."}},
    {ic:'p08', n:{ar:"رفيق المسلم الجديد",en:"The New Muslim Companion"},
      d:{ar:"مرشدٌ ذكيٌّ متعدد اللغات يرافقك ويجيب أسئلتك لحظةً بلحظة.",
         en:"A smart multilingual guide that walks with you and answers in the moment."}},
    {ic:'p09', n:{ar:"شبكة الدعوة",en:"Da'wah Network"},
      d:{ar:"الدعوة والتواصل العالمي لإيصال رسالة الرحمة إلى غير المسلمين — كافّةً للناس.",
         en:"Global outreach carrying the message of mercy to all humanity."}},
    {ic:'p10', n:{ar:"المكتبة الإسلامية الذكية",en:"Smart Islamic Library"},
      d:{ar:"قاعدة معرفةٍ وبحثٍ ذكيةٍ بمصادر موثوقة تخدم كل المشاريع.",
         en:"An intelligent, trusted knowledge base serving every project."}},
    {ic:'p11', n:{ar:"منصة البث",en:"Broadcast Platform"},
      d:{ar:"محتوىً مرئيٌّ هادفٌ يقرّب المفاهيم القرآنية بلغة العصر.",
         en:"Purposeful visual content bringing Qur'anic meanings closer."}},
    {ic:'p12', n:{ar:"صوت الهداية",en:"Voice of Guidance"},
      d:{ar:"بودكاست إذاعيٌّ يصل حيث لا تصل الشاشة، في كل وقتٍ ومكان.",
         en:"An audio podcast that reaches beyond the screen, anytime."}},
    {ic:'p13', n:{ar:"قلم الهداية",en:"Pen of Guidance"},
      d:{ar:"مقالاتٌ وبحوثٌ تعمّق الفهم وتردّ الشبهات بعلمٍ وبصيرة.",
         en:"Articles and research that deepen understanding and answer doubts."}},
    {ic:'p14', n:{ar:"معرض الهداية",en:"Guidance Gallery"},
      d:{ar:"تصاميم وإنفوجرافيك تبسّط المعاني القرآنية بصرياً.",
         en:"Designs and infographics that simplify meanings visually."}},
    {ic:'p15', n:{ar:"روزنامة المسلم",en:"The Muslim Calendar"},
      d:{ar:"مناسباتٌ وتذكيرٌ يواكب حياة المسلم اليومية ويربطها بالعبادة.",
         en:"Occasions and reminders woven into daily Muslim life."}},
    {ic:'p16', n:{ar:"جسور الترجمة",en:"Translation Bridges"},
      d:{ar:"بنية ترجمةٍ احترافية تجعل إضافة أي لغةٍ إدخالَ بياناتٍ لا إعادةَ بناء.",
         en:"A translation layer that makes adding any language plug-and-play."}},
    {ic:'p17', n:{ar:"لغات متعددة",en:"Many Languages"},
      d:{ar:"ثلاثون لغةً عالميةً بمسارين، وصولاً إلى لغة الإشارة لذوي الهمم.",
         en:"Thirty world languages on two tracks — up to sign language."}},
    {ic:'p18', n:{ar:"بوابة الدعم",en:"Support Gateway"},
      d:{ar:"تبرّعٌ آمنٌ ومستدام، يرى فيه الداعم أثره مباشرةً في لوحة شفافة.",
         en:"Safe, sustainable giving where donors see their impact directly."}},
    {ic:'p19', n:{ar:"وقف الهداية",en:"Guidance Endowment"},
      d:{ar:"أوقافٌ ومشاريع مستدامة: صدقةٌ جاريةٌ لا ينقطع أجرها.",
         en:"Sustainable endowments — an ongoing charity that never ceases."}},
    {ic:'p20', n:{ar:"التقارير والتأثير",en:"Reports & Impact"},
      d:{ar:"قياس الأثر والبيانات بشفافيةٍ كاملةٍ تعزّز ثقة الداعمين.",
         en:"Transparent impact and data measurement that builds trust."}},
    {ic:'p21', n:{ar:"الأمن والخصوصية",en:"Security & Privacy"},
      d:{ar:"حماية البيانات والخصوصية بالتصميم: أقلّ بياناتٍ وتشفيرٌ افتراضي.",
         en:"Data protection and privacy by design, from day one."}},
    {ic:'p22', n:{ar:"إدارة المستخدمين",en:"User Management"},
      d:{ar:"صلاحياتٌ ومتابعةٌ دقيقةٌ لرحلة كل مستخدمٍ عبر آلة الحالات.",
         en:"Precise roles and tracking across each user's journey."}},
    {ic:'p23', n:{ar:"لوحة الإدارة",en:"Admin Dashboard"},
      d:{ar:"إدارةٌ شاملةٌ لكل المشاريع والوحدات من مكانٍ واحد.",
         en:"Unified management of all projects and modules in one place."}}
  ],
  expansion: [
    {ar:"المساعد الذكي",en:"Smart Assistant"},{ar:"الأسرة المسلمة",en:"The Muslim Family"},
    {ar:"أطفال الهداية",en:"Guidance Kids"},{ar:"شباب الهداية",en:"Guidance Youth"},
    {ar:"مهارات الحياة",en:"Life Skills"},{ar:"الصحة الجسدية",en:"Physical Health"},
    {ar:"الصحة النفسية",en:"Mental Wellbeing"},{ar:"المال الحلال",en:"Halal Finance"},
    {ar:"ريادة الأعمال",en:"Entrepreneurship"},{ar:"متجر الهداية",en:"Guidance Store"},
    {ar:"دليل المسلم",en:"Muslim Directory"},{ar:"السياحة الحلال",en:"Halal Travel"},
    {ar:"تعلّم اللغات",en:"Language Learning"},{ar:"المبرمج المسلم",en:"The Muslim Coder"},
    {ar:"البيئة والمجتمع",en:"Environment & Society"},{ar:"العمل الخيري",en:"Charitable Work"},
    {ar:"المؤتمرات والفعاليات",en:"Events & Conferences"},{ar:"البحوث والدراسات",en:"Research & Studies"},
    {ar:"التراث الإسلامي",en:"Islamic Heritage"},{ar:"الابتكار والمبادرات",en:"Innovation & Initiatives"}
  ]
};
