// إهدنا — بيانات المشاريع الـ34 بثلاث لغات (تسويقي)
window.IHDINA_PROJECTS = {
  axes: [
    { id:"core",  icon:"★", color:"#b8862b",
      name:{ar:"المنتجات المحورية",en:"Core Products",de:"Kernprodukte"},
      tag:{ar:"العمود الفقري للمنظومة",en:"The backbone of the system",de:"Das Rückgrat des Systems"} },
    { id:"allah", icon:"◈", color:"#1f8f7d",
      name:{ar:"محور الله — الحُسنى",en:"The God Axis — Al-Husna",de:"Die Gottes-Achse — Al-Husna"},
      tag:{ar:"معرفة المعبود بأسمائه وصفاته",en:"Knowing God through His names and attributes",de:"Gott durch Seine Namen und Eigenschaften kennen"} },
    { id:"wahy",  icon:"✦", color:"#4a5ec1",
      name:{ar:"محور الوحي — الأحسن",en:"The Revelation Axis — Al-Ahsan",de:"Die Offenbarungs-Achse — Al-Ahsan"},
      tag:{ar:"اتّباع أحسن ما أُنزل",en:"Following the best of what was revealed",de:"Dem Besten des Offenbarten folgen"} },
    { id:"insan", icon:"❋", color:"#7d3fa8",
      name:{ar:"محور الإنسان — الإحسان",en:"The Human Axis — Al-Ihsan",de:"Die Menschen-Achse — Al-Ihsan"},
      tag:{ar:"أن تعبد الله كأنك تراه",en:"To worship God as if you see Him",de:"Gott anbeten, als sähest du Ihn"} },
    { id:"tech",  icon:"⬡", color:"#8a651d",
      name:{ar:"طبقة التمكين التقني",en:"Technology Enablement Layer",de:"Technologie-Ebene"},
      tag:{ar:"البنية الذكية التي تحمل كل شيء",en:"The intelligent infrastructure carrying it all",de:"Die intelligente Infrastruktur, die alles trägt"} }
  ],
  projects: [
    // ===== المحورية =====
    { axis:"core", star:true, icon:"📖",
      name:{ar:"التفسير التفاعلي الذكي",en:"The Intelligent Interactive Tafsir",de:"Der Intelligente Interaktive Tafsir"},
      pitch:{ar:"ليس تفسيراً يُقرأ بل مسارٌ يُسلَك: عش القرآن كما نزل أول مرة، كتلةً معرفيةً بعد كتلة، حتى يصير منهجَ حياتك.",
             en:"Not a tafsir you read — a path you walk. Live the Qur'an as it was first revealed, block by block, until it becomes your way of life.",
             de:"Kein Tafsir zum Lesen — ein Weg zum Gehen. Erlebe den Koran, wie er zuerst offenbart wurde, Block für Block, bis er dein Lebensweg wird."} },
    { axis:"core", star:true, icon:"🧭",
      name:{ar:"منصة إهدنا",en:"The IHDINA Platform",de:"Die IHDINA-Plattform"},
      pitch:{ar:"بوابتك الجامعة: تبدأ بتحليل شخصيتك وبيئتك، وتفتح لك الكتل المتدرجة، وترافقك خطوةً خطوة نحو الصراط المستقيم.",
             en:"Your gateway: it starts by understanding you and your environment, opens graded knowledge blocks, and walks with you step by step.",
             de:"Dein Tor: Es beginnt mit dir und deinem Umfeld, öffnet gestufte Wissensblöcke und begleitet dich Schritt für Schritt."} },
    { axis:"core", star:true, icon:"🏠",
      name:{ar:"دار الأرقم الثانية الذكية",en:"The Second Smart Dar al-Arqam",de:"Das Zweite Smarte Dar al-Arqam"},
      pitch:{ar:"كما احتضن النبي ﷺ من أسلم حديثاً في دار الأرقم — بيئة احتضان رقمية دافئة يجد فيها المسلم الجديد معلماً وصحبةً وأماناً.",
             en:"Just as the Prophet ﷺ embraced new Muslims in Dar al-Arqam — a warm digital incubator where every new Muslim finds a teacher, companions and safety.",
             de:"Wie der Prophet ﷺ neue Muslime im Dar al-Arqam aufnahm — ein warmer digitaler Schutzraum mit Lehrer, Gemeinschaft und Sicherheit."} },
    { axis:"core", star:true, icon:"📿",
      name:{ar:"ورد المحاسبة اليومية",en:"The Daily Accountability Wird",de:"Der Tägliche Rechenschafts-Wird"},
      pitch:{ar:"التطبيق الصغير المتراكم يصنع التحول الكبير: قياس يومي موزون على المحاور الثلاثة يحوّل الفهم إلى سلوك يُرى ويُقاس.",
             en:"Small daily practice creates great transformation: a balanced daily measure across three axes turns understanding into visible, measurable character.",
             de:"Kleine tägliche Praxis schafft große Verwandlung: ein tägliches Maß auf drei Achsen macht Verständnis zu sichtbarem Verhalten."} },
    // ===== محور الله =====
    { axis:"allah", icon:"✨",
      name:{ar:"الأسماء الحسنى",en:"The Most Beautiful Names",de:"Die Schönsten Namen"},
      pitch:{ar:"من الحفظ إلى العيش: كل اسم من أسماء الله يتحول إلى سلوك يومي تلمسه في قلبك وأخلاقك.",
             en:"From memorizing to living: every divine name becomes a daily practice you feel in your heart and character.",
             de:"Vom Auswendiglernen zum Leben: Jeder Gottesname wird zu täglicher Praxis in Herz und Charakter."} },
    { axis:"allah", icon:"💫",
      name:{ar:"من هو الله؟",en:"Who Is God?",de:"Wer ist Gott?"},
      pitch:{ar:"السؤال الأول لكل مهتدٍ جديد — إجابة قرآنية صافية تصحح التصور وتبني توحيداً خالصاً من المنبع.",
             en:"The first question of every new believer — a pure Qur'anic answer that corrects misconceptions and builds tawhid from the source.",
             de:"Die erste Frage jedes neuen Gläubigen — eine reine koranische Antwort, die Vorstellungen korrigiert und Tauhid von der Quelle aufbaut."} },
    { axis:"allah", icon:"🔚",
      name:{ar:"خواتيم الآيات",en:"Verse Endings",de:"Versabschlüsse"},
      pitch:{ar:"لماذا ختم الله هذه الآية بـ«عزيز حكيم» وتلك بـ«غفور رحيم»؟ تدبر المقاصد في أدق تفاصيل الخطاب.",
             en:"Why does one verse end with 'Mighty, Wise' and another with 'Forgiving, Merciful'? Discover divine intent in the finest details.",
             de:"Warum endet ein Vers mit „Mächtig, Weise\" und ein anderer mit „Vergebend, Barmherzig\"? Entdecke die göttliche Absicht im Detail."} },
    { axis:"allah", icon:"📜",
      name:{ar:"مراد الله في القصص",en:"God's Intent in the Stories",de:"Gottes Absicht in den Geschichten"},
      pitch:{ar:"خمسون قصة قرآنية بقالب واحد مؤكد بدقة 100% — استخرج مراد الله منها لحياتك أنت.",
             en:"Fifty Qur'anic stories, one verified template with 100% accuracy — extract God's intent for your own life.",
             de:"Fünfzig Korangeschichten, eine bestätigte Vorlage mit 100% Genauigkeit — für dein eigenes Leben."} },
    // ===== محور الوحي =====
    { axis:"wahy", icon:"⚛️",
      name:{ar:"منظومة الهداية — المفاعل النووي",en:"The Guidance System — Nuclear Reactor",de:"Das Führungssystem — Nuklearreaktor"},
      pitch:{ar:"كما يتحكم المفاعل في الطاقة، يتحكم مفاعل الهداية في تسلسل الكتل المعرفية — ليُنتج تحولاً روحياً مستداماً لا حماسة عابرة.",
             en:"As a reactor controls energy, the Guidance Reactor controls the sequence of knowledge blocks — producing sustained spiritual transformation, not fleeting enthusiasm.",
             de:"Wie ein Reaktor Energie steuert, steuert der Führungsreaktor die Wissensblöcke — für nachhaltige geistige Verwandlung statt flüchtiger Begeisterung."} },
    { axis:"wahy", icon:"⚗️",
      name:{ar:"مفاعل الاستنباط القرآني",en:"The Qur'anic Derivation Reactor",de:"Der Koranische Ableitungsreaktor"},
      pitch:{ar:"محرك يولّد المفاهيم والأحكام من النص مباشرة — البحث القرآني العميق في خدمة كل مسلم.",
             en:"An engine deriving concepts and rulings directly from the text — deep Qur'anic research serving every Muslim.",
             de:"Eine Engine, die Konzepte und Urteile direkt aus dem Text ableitet — tiefe Koranforschung für jeden Muslim."} },
    { axis:"wahy", icon:"🕌",
      name:{ar:"محاكاة الأنبياء وأولي العزم",en:"Simulating the Prophets of Resolve",de:"Simulation der Propheten der Entschlossenheit"},
      pitch:{ar:"تفاعل مع مسارات الأنبياء: كيف صبر نوح؟ كيف واجه إبراهيم قومه؟ دروس حية تحاكيها لا تقرؤها فقط.",
             en:"Interact with the prophets' journeys: How did Noah persevere? How did Abraham face his people? Living lessons you experience, not just read.",
             de:"Interagiere mit den Wegen der Propheten: Wie hielt Noah durch? Wie begegnete Abraham seinem Volk? Lebendige Lektionen zum Erleben."} },
    { axis:"wahy", icon:"👣",
      name:{ar:"التابع المحمدي",en:"The Muhammadan Follower",de:"Der Muhammadanische Nachfolger"},
      pitch:{ar:"«كان خلقه القرآن» — محاكاة الاقتداء العملي بالنبي ﷺ في يومك: كيف كان سيتصرف في موقفك أنت؟",
             en:"'His character was the Qur'an' — practical emulation of the Prophet ﷺ in your day: how would he act in your situation?",
             de:"„Sein Charakter war der Koran\" — praktische Nachahmung des Propheten ﷺ im Alltag: Wie hätte er in deiner Lage gehandelt?"} },
    { axis:"wahy", icon:"📢",
      name:{ar:"المبلّغ — على بصيرة",en:"The Messenger — With Insight",de:"Der Verkünder — Mit Einsicht"},
      pitch:{ar:"﴿أدعو إلى الله على بصيرة﴾ — إعداد الداعية الرقمي الذي يبلّغ بعلم لا بحماس فقط.",
             en:"'I call to God with insight' — preparing digital preachers who convey with knowledge, not enthusiasm alone.",
             de:"„Ich rufe zu Gott mit Einsicht\" — Ausbildung digitaler Prediger, die mit Wissen verkünden."} },
    { axis:"wahy", icon:"🌱",
      name:{ar:"مصعب بن عمير",en:"Mus'ab ibn Umayr",de:"Mus'ab ibn Umayr"},
      pitch:{ar:"سفير الإسلام الأول الذي أسلمت المدينة على يديه شاباً — نموذج الداعية الشاب المؤسِّس لجيل القادة الجدد.",
             en:"Islam's first ambassador who won Madinah as a young man — the model of the young founding preacher for a new generation of leaders.",
             de:"Der erste Botschafter des Islam, der Medina als junger Mann gewann — das Vorbild für eine neue Führungsgeneration."} },
    { axis:"wahy", icon:"💯",
      name:{ar:"مشروع 114",en:"Project 114",de:"Projekt 114"},
      pitch:{ar:"كل سورة من السور الـ114 كتلة متكاملة لها شخصيتها ومسارها — اكتشف خريطة القرآن سورةً سورة.",
             en:"Each of the 114 surahs as a complete unit with its own character and path — discover the Qur'an's map, surah by surah.",
             de:"Jede der 114 Suren als vollständige Einheit mit eigenem Charakter und Weg — entdecke die Landkarte des Korans."} },
    { axis:"wahy", icon:"🎯",
      name:{ar:"مشروع 50S",en:"Project 50S",de:"Projekt 50S"},
      pitch:{ar:"خمسون محطة منهجية للترقي — سلّم واضح من أول خطوة إلى القيادة الدعوية.",
             en:"Fifty methodical stations of ascent — a clear ladder from the first step to leadership.",
             de:"Fünfzig methodische Aufstiegsstationen — eine klare Leiter vom ersten Schritt zur Führung."} },
    { axis:"wahy", icon:"🕊️",
      name:{ar:"أطايب الكلم",en:"The Finest of Words",de:"Die Schönsten Worte"},
      pitch:{ar:"الذكر والكلم الطيب في سياقه القرآني — ليكون لسانك رطباً بما أحب الله.",
             en:"Remembrance and good words in their Qur'anic context — so your tongue stays moist with what God loves.",
             de:"Gedenken und gute Worte im koranischen Kontext — damit deine Zunge feucht bleibt mit dem, was Gott liebt."} },
    { axis:"wahy", icon:"🔬",
      name:{ar:"الإعجاز العلمي والرقمي",en:"Scientific & Numerical Miracles",de:"Wissenschaftliche & Numerische Wunder"},
      pitch:{ar:"أدلة عقلية معاصرة تدعم الفهم — للعقل الغربي الباحث عن برهان قبل الإيمان.",
             en:"Contemporary rational evidence supporting faith — for the analytical mind that seeks proof before belief.",
             de:"Zeitgenössische rationale Belege für den Glauben — für den analytischen Verstand, der Beweise sucht."} },
    { axis:"wahy", icon:"📈",
      name:{ar:"نمو المفاهيم القرآنية",en:"Growth of Qur'anic Concepts",de:"Wachstum Koranischer Konzepte"},
      pitch:{ar:"كيف نما مفهوم «الصبر» عبر 23 سنة من التنزيل؟ تتبع تراكمي يكشف عبقرية التدرج الرباني.",
             en:"How did 'patience' grow across 23 years of revelation? Cumulative tracking revealing the genius of divine gradualism.",
             de:"Wie wuchs „Geduld\" über 23 Jahre der Offenbarung? Kumulative Verfolgung, die die Genialität göttlicher Stufung zeigt."} },
    { axis:"wahy", icon:"🔄",
      name:{ar:"مجددون",en:"Renewers",de:"Erneuerer"},
      pitch:{ar:"«يبعث لهذه الأمة على رأس كل مائة سنة من يجدد لها دينها» — إعداد مجددي الفهم والتنزيل على الواقع.",
             en:"Preparing those who renew understanding and application for each generation — renewal of insight, never alteration of text.",
             de:"Ausbildung derer, die Verständnis und Anwendung für jede Generation erneuern — Erneuerung der Einsicht, nie des Textes."} },
    { axis:"wahy", icon:"⚖️",
      name:{ar:"أحق بها",en:"Most Worthy of It",de:"Ihrer Am Würdigsten"},
      pitch:{ar:"الحكمة ضالة المؤمن — من وجدها فهو أحق بها. مشروع استحقاق الحكمة والعمل بها.",
             en:"Wisdom is the believer's lost treasure — whoever finds it is most worthy of it. Deserving wisdom by living it.",
             de:"Weisheit ist der verlorene Schatz des Gläubigen — wer sie findet, ist ihrer am würdigsten."} },
    // ===== محور الإنسان =====
    { axis:"insan", icon:"🌷",
      name:{ar:"مشروع مريم",en:"Project Maryam",de:"Projekt Maryam"},
      pitch:{ar:"﴿إن الله اصطفاك وطهرك﴾ — للمسلمة الجديدة مشروع كامل باسم أعظم امرأة: قدوة وتزكية ومجتمع نسائي آمن.",
             en:"For the new Muslimah, a complete project named after the greatest of women: role models, purification, and a safe women's community.",
             de:"Für die neue Muslimin ein komplettes Projekt im Namen der größten Frau: Vorbilder, Läuterung und eine sichere Frauengemeinschaft."} },
    { axis:"insan", icon:"💪",
      name:{ar:"تحليل الشخصية — القوي الأمين",en:"Personality Analysis — Strong & Trustworthy",de:"Persönlichkeitsanalyse — Stark & Vertrauenswürdig"},
      pitch:{ar:"﴿إن خير من استأجرت القوي الأمين﴾ — اكتشف نمطك القرآني ومراتب نفسك قبل أن تبدأ رحلتك.",
             en:"'The best you can hire is the strong and trustworthy' — discover your Qur'anic type and the states of your soul before your journey begins.",
             de:"Entdecke deinen koranischen Typ und die Zustände deiner Seele, bevor deine Reise beginnt."} },
    { axis:"insan", icon:"🌍",
      name:{ar:"تحليل البيئة — أم القرى",en:"Environment Analysis — Umm al-Qura",de:"Umfeldanalyse — Umm al-Qura"},
      pitch:{ar:"بيئتك داعمة أم صعبة؟ منهج «أم القرى» يقيس محيطك ليختار استراتيجيتك — فما يناسب برلين غير ما يناسب جاكرتا.",
             en:"Is your environment supportive or hostile? The Umm al-Qura method measures your context to choose your strategy — Berlin differs from Jakarta.",
             de:"Ist dein Umfeld unterstützend oder schwierig? Die Umm-al-Qura-Methode misst deinen Kontext — Berlin ist nicht Jakarta."} },
    { axis:"insan", icon:"📋",
      name:{ar:"بروتوكولات المسلم الذكية",en:"Smart Muslim Protocols",de:"Smarte Muslim-Protokolle"},
      pitch:{ar:"إجراءات يومية عملية موجهة: أول صلاة، أول رمضان، أول موقف صعب — دليل خطوة بخطوة لكل «أول مرة».",
             en:"Guided practical routines: your first prayer, first Ramadan, first difficult moment — a step-by-step guide for every 'first time'.",
             de:"Geführte praktische Routinen: dein erstes Gebet, erster Ramadan, erster schwieriger Moment — Schritt für Schritt."} },
    { axis:"insan", icon:"🤝",
      name:{ar:"منصة المسلمين الجدد",en:"The New Muslims Platform",de:"Die Plattform für Neue Muslime"},
      pitch:{ar:"لن تمشي وحدك: احتضان ومرافقة وتوأمة مع مرشد يفهم رحلتك — من لحظة الشهادة إلى الثبات.",
             en:"You will never walk alone: embrace, companionship and twinning with a mentor who understands your journey — from shahada to steadfastness.",
             de:"Du gehst nie allein: Aufnahme, Begleitung und Partnerschaft mit einem Mentor — von der Schahada bis zur Festigkeit."} },
    { axis:"insan", icon:"🚪",
      name:{ar:"اكتشاف الإسلام كافة",en:"Discover Islam Entirely",de:"Den Islam Ganz Entdecken"},
      pitch:{ar:"بوابة التعريف الشامل بالإسلام لغير المسلمين — الدين نقياً من منبعه، بلسان العصر.",
             en:"The comprehensive gateway to Islam for non-Muslims — the faith pure from its source, in the language of our time.",
             de:"Das umfassende Tor zum Islam für Nichtmuslime — der Glaube rein von seiner Quelle, in der Sprache unserer Zeit."} },
    { axis:"insan", icon:"🫶",
      name:{ar:"الدعوة للفئات الخاصة",en:"Outreach for Special Needs",de:"Dawa für Besondere Bedürfnisse"},
      pitch:{ar:"لغة الإشارة ومحتوى موائم لذوي الهمم — لأن رسالة القرآن ﴿كافة للناس﴾ بلا استثناء.",
             en:"Sign language and adapted content for people of determination — because the Qur'an's message is 'for all humanity', no exceptions.",
             de:"Gebärdensprache und angepasste Inhalte — denn die Botschaft des Korans gilt „der ganzen Menschheit\", ohne Ausnahme."} },
    { axis:"insan", icon:"🧹",
      name:{ar:"عافية — النقاء",en:"Afiyah — Purity",de:"Afiyah — Reinheit"},
      pitch:{ar:"التخلية قبل التحلية: طهارة القلب من أدرانه — أول خطوات التزكية الحقيقية.",
             en:"Emptying before adorning: purifying the heart of its ailments — the first step of true self-refinement.",
             de:"Leeren vor dem Schmücken: das Herz von seinen Leiden reinigen — der erste Schritt wahrer Läuterung."} },
    { axis:"insan", icon:"💎",
      name:{ar:"تحلية — الإحسان المستدام",en:"Tahliyah — Sustainable Excellence",de:"Tahliyah — Nachhaltige Vortrefflichkeit"},
      pitch:{ar:"بعد النقاء تأتي التحلية بالفضائل — إحسان يستمر ولا ينطفئ بعد حماسة البداية.",
             en:"After purity comes adornment with virtues — excellence that endures beyond the enthusiasm of beginnings.",
             de:"Nach der Reinheit kommt das Schmücken mit Tugenden — Vortrefflichkeit, die über den Anfangseifer hinaus besteht."} },
    { axis:"insan", icon:"🫀",
      name:{ar:"رعاية الجسد — سليم",en:"Body Care — Saleem",de:"Körperpflege — Saleem"},
      pitch:{ar:"جسدك أمانة: صحة البدن عبادة — نوم وغذاء وحركة على هدي الوحي.",
             en:"Your body is a trust: physical health as worship — sleep, nutrition and movement guided by revelation.",
             de:"Dein Körper ist ein anvertrautes Gut: Gesundheit als Gottesdienst — Schlaf, Ernährung und Bewegung nach der Offenbarung."} },
    { axis:"insan", icon:"⛰️",
      name:{ar:"غار حراء",en:"Cave of Hira",de:"Höhle von Hira"},
      pitch:{ar:"قبل الوحي كانت الخلوة — مساحتك الرقمية للتزود الروحي والانقطاع المنظم عن الضجيج.",
             en:"Before revelation came retreat — your digital space for spiritual replenishment and structured disconnection from the noise.",
             de:"Vor der Offenbarung kam der Rückzug — dein digitaler Raum für spirituelle Stärkung und strukturierte Stille."} },
    // ===== التقنية =====
    { axis:"tech", icon:"📚",
      name:{ar:"المكتبة الإسلامية الذكية",en:"The Smart Islamic Library",de:"Die Smarte Islamische Bibliothek"},
      pitch:{ar:"قاعدة معرفة وبحث ذكية مشتركة تخدم كل المشاريع — اسأل فتجيبك المصادر الموثقة لا التخمين.",
             en:"A shared intelligent knowledge base serving all projects — ask, and verified sources answer, not guesswork.",
             de:"Eine gemeinsame intelligente Wissensbasis für alle Projekte — frage, und geprüfte Quellen antworten."} },
    { axis:"tech", icon:"🎨",
      name:{ar:"البحوث والكتب المصوّرة",en:"Visual Research & Books",de:"Visuelle Forschung & Bücher"},
      pitch:{ar:"المعرفة العميقة في صورة بصرية جذابة — لجيل يقرأ بعينيه قبل عقله.",
             en:"Deep knowledge in captivating visual form — for a generation that reads with its eyes before its mind.",
             de:"Tiefes Wissen in fesselnder visueller Form — für eine Generation, die mit den Augen liest."} },
    { axis:"tech", icon:"🧬",
      name:{ar:"LIFEQ OS — نظام تشغيل الحياة",en:"LIFEQ OS — The Life Operating System",de:"LIFEQ OS — Das Lebens-Betriebssystem"},
      pitch:{ar:"الطبقة الجامعة: نظام تشغيل حياتك وفق القرآن — كل المشاريع تصب فيه ليدير يومك من الفجر إلى الفجر.",
             en:"The unifying layer: your life's operating system according to the Qur'an — every project feeds into it, running your day from dawn to dawn.",
             de:"Die verbindende Ebene: das Betriebssystem deines Lebens nach dem Koran — von Morgengrauen zu Morgengrauen."} }
  ]
};
